import { beforeAll, afterAll, describe, expect, it } from "vitest";
import { randomUUID } from "node:crypto";
import pg from "pg";
import type { Job, ExecutionInput, ProgressSummary } from "@nucleo/core";
import { exerciseDefinitions } from "@nucleo/content/server";
const base = "http://127.0.0.1:3060/api";
const origin = process.env.PUBLIC_ORIGIN!;
type Account = { cookie: string; id: string; email: string };
const pool = new pg.Pool({
  connectionString: process.env.MIGRATION_DATABASE_URL,
  max: 2,
});
const accounts: Account[] = [];
async function request(
  path: string,
  account?: Account,
  payload?: unknown,
  method = payload ? "POST" : "GET",
  requestOrigin = origin,
) {
  return fetch(`${base}${path}`, {
    method,
    headers: {
      origin: requestOrigin,
      "Content-Type": "application/json",
      ...(account ? { cookie: account.cookie } : {}),
    },
    ...(payload ? { body: JSON.stringify(payload) } : {}),
  });
}
async function signup(): Promise<Account> {
  const email = `integration-${randomUUID()}@example.invalid`;
  const response = await request("/auth/sign-up/email", undefined, {
    name: "Teste de integração",
    email,
    password: "Nucleo-Integration-2026-seguro",
  });
  expect(response.status).toBe(200);
  const result = (await response.json()) as { user: { id: string } };
  const account = {
    id: result.user.id,
    email,
    cookie: response.headers
      .getSetCookie()
      .map((item) => item.split(";")[0])
      .join("; "),
  };
  accounts.push(account);
  return account;
}
async function enqueue(
  code: string,
  language: ExecutionInput["language"] = "python",
  account = accounts[0]!,
) {
  const extension =
    language === "python"
      ? "py"
      : language === "c"
        ? "c"
        : language === "windows-cpp"
          ? "cpp"
          : "asm";
  const response = await request("/executions", account, {
    language,
    files: [{ name: `main.${extension}`, content: code }],
    entryFile: `main.${extension}`,
    submissionId: randomUUID(),
    mode: "x86-64",
  });
  expect(response.status).toBe(202);
  return response.json() as Promise<Job>;
}
async function waitFor(job: Job, account = accounts[0]!) {
  const until = Date.now() + 35000;
  while (Date.now() < until) {
    const value = (await (
      await request(`/executions/${job.id}`, account)
    ).json()) as Job;
    if (
      !["queued", "provisioning", "running", "compiling"].includes(value.status)
    )
      return value;
    await new Promise((resolve) => setTimeout(resolve, 150));
  }
  throw new Error("Execution did not finish within the test deadline.");
}
let lessonId = "";
beforeAll(async () => {
  await signup();
  await signup();
  const catalog = (await (await request("/catalog")).json()) as {
    modules: { lessons: { id: string }[] }[];
  };
  lessonId = catalog.modules[0]!.lessons[0]!.id;
});
afterAll(async () => {
  // Only the accounts generated by this suite are removed.
  if (accounts.length)
    await pool.query("DELETE FROM users WHERE id = ANY($1::text[])", [
      accounts.map((account) => account.id),
    ]);
  await pool.end();
});
describe("Sessões, autorização e progresso persistente", () => {
  it("exige sessão e origem confiável", async () => {
    expect((await request("/progress")).status).toBe(401);
    expect(
      (
        await request(
          "/progress/complete",
          accounts[0],
          { lessonId, eventId: randomUUID() },
          "POST",
          "https://untrusted.invalid",
        )
      ).status,
    ).toBe(403);
  });
  it("conclui uma única vez sob concorrência e restaura em nova sessão", async () => {
    const responses = await Promise.all(
      Array.from({ length: 5 }, () =>
        request("/progress/complete", accounts[0], {
          lessonId,
          eventId: randomUUID(),
        }),
      ),
    );
    expect(responses.every((response) => response.ok)).toBe(true);
    const summary = (await (
      await request("/progress", accounts[0])
    ).json()) as ProgressSummary;
    expect(summary.completedLessons).toBe(1);
    expect(
      summary.activities.filter((event) => event.kind === "lesson_completed"),
    ).toHaveLength(1);
    const isolated = (await (
      await request("/progress", accounts[1])
    ).json()) as ProgressSummary;
    expect(isolated.completedLessons).toBe(0);
    await request("/auth/sign-out", accounts[0], {});
    expect((await request("/progress", accounts[0])).status).toBe(401);
    const login = await request("/auth/sign-in/email", undefined, {
      email: accounts[0]!.email,
      password: "Nucleo-Integration-2026-seguro",
    });
    expect(login.status).toBe(200);
    accounts[0]!.cookie = login.headers
      .getSetCookie()
      .map((item) => item.split(";")[0])
      .join("; ");
    expect(
      (
        (await (
          await request("/progress", accounts[0])
        ).json()) as ProgressSummary
      ).completedLessons,
    ).toBe(1);
  });
  it("salva rascunhos com controle de concorrência e isolamento por conta", async () => {
    const payload = {
      files: [{ name: "main.py", content: "print(1)" }],
      language: "python",
      activeFile: "main.py",
      expectedVersion: 0,
    };
    expect(
      (
        await request(
          "/assessments/drafts/playground-python",
          accounts[0],
          payload,
          "PUT",
        )
      ).status,
    ).toBe(200);
    const writes = await Promise.all(
      [2, 3].map((value) =>
        request(
          "/assessments/drafts/playground-python",
          accounts[0],
          {
            ...payload,
            expectedVersion: 1,
            files: [{ name: "main.py", content: `print(${value})` }],
          },
          "PUT",
        ),
      ),
    );
    expect(writes.map((response) => response.status).sort()).toEqual([
      200, 409,
    ]);
    expect(
      await (
        await request("/assessments/drafts/playground-python", accounts[1])
      ).json(),
    ).toBeNull();
    expect(
      (
        (await (
          await request("/assessments/drafts/playground-python", accounts[0])
        ).json()) as { version: number }
      ).version,
    ).toBe(2);
  });
  it("registra complementos sem duplicar o evento de conclusão", async () => {
    for (let i = 0; i < 2; i++)
      expect(
        (
          await request("/assessments/supplement", accounts[0], {
            id: "ponto-flutuante",
            answer: "23 bits",
            submissionId: randomUUID(),
          })
        ).status,
      ).toBe(200);
    const summary = (await (
      await request("/progress", accounts[0])
    ).json()) as ProgressSummary;
    expect(summary.passedExercises).toBe(1);
    expect(
      summary.activities.filter(
        (event) => event.kind === "experiment_completed",
      ),
    ).toHaveLength(1);
  });
  it("separa as permissões do runner e da aplicação no PostgreSQL", async () => {
    const result = await pool.query(
      "SELECT has_table_privilege('nucleo_runner','sessions','SELECT') AS sessions, has_table_privilege('nucleo_app','execution_jobs','INSERT') AS jobs, (SELECT rolsuper FROM pg_roles WHERE rolname='nucleo_app') AS superuser",
    );
    expect(result.rows[0]).toEqual({
      sessions: false,
      jobs: true,
      superuser: false,
    });
  });
});
describe("Execução real em gVisor", () => {
  it("executa Python com rede bloqueada, usuário restrito e sem credenciais", async () => {
    const code =
      'import os, socket\nprint("uid", os.geteuid())\nprint("credentials", "DATABASE_URL" in os.environ or "BETTER_AUTH_SECRET" in os.environ)\ns=socket.socket()\ns.settimeout(1)\ntry:\n s.connect(("1.1.1.1", 80))\n print("network open")\nexcept OSError:\n print("network blocked")\n';
    const queued = await enqueue(code);
    expect(
      (await request(`/executions/${queued.id}`, accounts[1])).status,
    ).toBe(404);
    const job = await waitFor(queued);
    expect(job.status).toBe("succeeded");
    expect(job.result?.stdout).toContain("uid 1000");
    expect(job.result?.stdout).toContain("credentials False");
    expect(job.result?.stdout).toContain("network blocked");
  });
  it("compila e executa C fora da API", async () => {
    const job = await waitFor(
      await enqueue(
        '#include <stdio.h>\nint main(void){printf("resultado=%d",6*7);return 0;}',
        "c",
      ),
    );
    expect(job.status).toBe("succeeded");
    expect(job.result?.stdout).toBe("resultado=42");
  });
  it("executa CALL/RET no modelo isolado", async () => {
    const job = await waitFor(
      await enqueue(
        "mov ecx, 3\nmov edx, 4\ncall soma\njmp fim\nsoma:\nadd ecx, edx\nmov eax, ecx\nret\nfim:\nnop",
        "assembly",
      ),
    );
    expect(job.status).toBe("succeeded");
    expect(BigInt(job.result!.cpu!.registers.RAX!)).toBe(7n);
  });
  it("gera um PE pelo FASM e autoriza o download somente ao dono", async () => {
    const job = await waitFor(
      await enqueue(
        "format PE64 GUI\nentry start\nsection '.text' code readable executable\nstart:\nmov eax, 1\nret",
        "fasm",
      ),
    );
    expect(job.status).toBe("succeeded");
    const id = job.result?.artifacts[0]?.id;
    expect(id).toBeTruthy();
    expect(
      (await request(`/executions/artifacts/${id}`, accounts[1])).status,
    ).toBe(404);
    const response = await request(`/executions/artifacts/${id}`, accounts[0]);
    expect(response.status).toBe(200);
    expect([
      ...new Uint8Array(await response.arrayBuffer()).slice(0, 2),
    ]).toEqual([0x4d, 0x5a]);
  });
  it("limita output e tempo de parede", async () => {
    const output = await waitFor(await enqueue('print("a" * 90000)'));
    expect(output.status).toBe("output_limited");
    expect(output.result?.stdout.length).toBeLessThanOrEqual(65536);
    const timeout = await waitFor(await enqueue("import time\ntime.sleep(20)"));
    expect(timeout.status).toBe("timed_out");
  });
  it("cancela uma tarefa em execução e mantém a conclusão monotônica", async () => {
    const job = await enqueue("import time\ntime.sleep(20)");
    await new Promise((resolve) => setTimeout(resolve, 900));
    expect(
      (await request(`/executions/${job.id}/cancel`, accounts[0], {})).status,
    ).toBe(200);
    expect((await waitFor(job)).status).toBe("cancelled");
    await new Promise((resolve) => setTimeout(resolve, 1300));
    expect((await waitFor(job)).status).toBe("cancelled");
  });
});

describe("Coleção de exercícios e evidência de execução", () => {
  it("publica 45 exercícios sem respostas e exige uma tentativa própria para a solução", async () => {
    const rows = (await (await request("/exercises")).json()) as Record<
      string,
      unknown
    >[];
    expect(rows).toHaveLength(45);
    for (const row of rows)
      for (const key of ["answer", "criteria", "solutionCode", "explanation"])
        expect(row).not.toHaveProperty(key);
    expect((await request("/exercises/progress")).status).toBe(401);
    expect(
      (
        await request(
          "/exercises/hexadecimal-para-decimal/solution",
          accounts[1],
        )
      ).status,
    ).toBe(403);
    expect(
      (
        await request("/exercises/hexadecimal-para-decimal/check", undefined, {
          answer: "42",
          submissionId: randomUUID(),
        })
      ).status,
    ).toBe(401);
    expect(
      (
        await request(
          "/exercises/hexadecimal-para-decimal/check",
          accounts[0],
          { answer: "42", passed: true, submissionId: randomUUID() },
        )
      ).status,
    ).toBe(400);
  });
  it("corrige respostas, restaura progresso e registra uma conclusão sob concorrência", async () => {
    const id = "hexadecimal-para-decimal";
    const incorrect = (await (
      await request(`/exercises/${id}/check`, accounts[0], {
        answer: "41",
        submissionId: randomUUID(),
      })
    ).json()) as { passed: boolean };
    expect(incorrect.passed).toBe(false);
    expect(
      (await request(`/exercises/${id}/solution`, accounts[0])).status,
    ).toBe(200);
    const before = (await (
      await request("/progress", accounts[0])
    ).json()) as ProgressSummary;
    const results = await Promise.all(
      Array.from({ length: 4 }, () =>
        request(`/exercises/${id}/check`, accounts[0], {
          answer: "0b101010",
          submissionId: randomUUID(),
        }),
      ),
    );
    for (const response of results)
      expect(((await response.json()) as { passed: boolean }).passed).toBe(
        true,
      );
    const after = (await (
      await request("/progress", accounts[0])
    ).json()) as ProgressSummary;
    expect(after.passedExercises).toBe(before.passedExercises + 1);
    expect(
      after.activities.filter(
        (event) =>
          event.kind === "exercise_completed" &&
          event.label === "Ler um valor hexadecimal",
      ),
    ).toHaveLength(1);
    expect(
      await (await request("/exercises/progress", accounts[0])).json(),
    ).toMatchObject({ completed: [id], attempted: [id] });
    expect(
      await (await request("/exercises/progress", accounts[1])).json(),
    ).toEqual({ completed: [], attempted: [] });
  });
  it("mantém uma submissão idempotente mesmo quando a resposta do reenvio muda", async () => {
    const submissionId = randomUUID(),
      id = "limite-de-um-byte";
    const first = await request(`/exercises/${id}/check`, accounts[0], {
      answer: "255",
      submissionId,
    });
    expect(((await first.json()) as { passed: boolean }).passed).toBe(true);
    const replay = await request(`/exercises/${id}/check`, accounts[0], {
      answer: "254",
      submissionId,
    });
    expect(((await replay.json()) as { passed: boolean }).passed).toBe(true);
    expect(
      (
        await request(`/exercises/${id}/check`, accounts[1], {
          answer: "255",
          submissionId,
        })
      ).status,
    ).toBe(409);
  });
  it("confere as oito soluções de programação em containers reais e associa cada execução", async () => {
    for (const exercise of exerciseDefinitions) {
      if (exercise.kind !== "code") continue;
      const extension =
        exercise.language === "python"
          ? "py"
          : exercise.language === "c"
            ? "c"
            : "asm";
      const payload = {
        language: exercise.language,
        mode: exercise.mode,
        files: [{ name: `main.${extension}`, content: exercise.solutionCode }],
        entryFile: `main.${extension}`,
        labId: exercise.labId,
        exerciseId: exercise.id,
        submissionId: randomUUID(),
      };
      const response = await request("/executions", accounts[0], payload);
      expect(response.status, exercise.id).toBe(202);
      const job = await waitFor((await response.json()) as Job);
      expect(job.status, exercise.id).toBe("succeeded");
      const result = await request(
        `/exercises/${exercise.id}/check`,
        accounts[0],
        { jobId: job.id, submissionId: randomUUID() },
      );
      expect(
        ((await result.json()) as { passed: boolean }).passed,
        exercise.id,
      ).toBe(true);
      expect(
        (
          await request(`/exercises/${exercise.id}/check`, accounts[1], {
            jobId: job.id,
            submissionId: randomUUID(),
          })
        ).status,
      ).toBe(400);
      const other = exerciseDefinitions.find(
        (item) => item.kind === "code" && item.id !== exercise.id,
      )!;
      expect(
        (
          await request(`/exercises/${other.id}/check`, accounts[0], {
            jobId: job.id,
            submissionId: randomUUID(),
          })
        ).status,
      ).toBe(400);
    }
  });
  it("rejeita aprovação fabricada e ambientes incompatíveis com o exercício", async () => {
    expect(
      (
        await request("/executions", accounts[0], {
          language: "python",
          mode: "x86-64",
          entryFile: "main.py",
          files: [{ name: "main.py", content: "print(42)" }],
          exerciseId: "assembly-produzir-42",
          submissionId: randomUUID(),
        })
      ).status,
    ).toBe(400);
    expect(
      (
        await request("/exercises/assembly-produzir-42/check", accounts[0], {
          answer: "42",
          submissionId: randomUUID(),
        })
      ).status,
    ).toBe(400);
    expect(
      (
        await request("/exercises/assembly-produzir-42/check", accounts[0], {
          jobId: randomUUID(),
          submissionId: randomUUID(),
        })
      ).status,
    ).toBe(400);
  });
  it("encerra um payload inválido sem bloquear as próximas tarefas da fila", async () => {
    const id = randomUUID();
    const payload = {
      language: "python",
      mode: "x86-64",
      entryFile: "main.py",
      files: [{ name: "main.py", content: "print(1)" }],
      submissionId: randomUUID(),
      invalidTestField: true,
    };
    await pool.query(
      "INSERT INTO execution_jobs (id,user_id,submission_id,payload,status) VALUES ($1,$2,$3,$4,$5)",
      [
        id,
        accounts[0]!.id,
        payload.submissionId,
        JSON.stringify(payload),
        "queued",
      ],
    );
    const malformed: Job = {
      id,
      language: "python",
      status: "queued",
      createdAt: new Date().toISOString(),
      result: null,
    };
    expect((await waitFor(malformed)).status).toBe("failed");
    const next = await waitFor(await enqueue('print("fila-livre")'));
    expect(next.status).toBe("succeeded");
    expect(next.result?.stdout).toBe("fila-livre\n");
  });
});
